apiVersion: v1
kind: Template
metadata:
  name: cluster-deployment-create-template

parameters:
- name: CLUSTER_NAME
  displayName: Cluster Name
  description: The name to give to the Cluster created. If using real AWS, then this name should include your username so that resources created in AWS can be identified as yours.
  required: true
- name: CLUSTER_NAMESPACE
  displayName: Cluster Namespace
  description: The namespace where the cluster should be created.
  value: openshift-cluster-operator
  required: true
- name: CLUSTER_VERSION
  displayName: Cluster Version
  description: Cluster version to install.
- name: CLUSTER_VERSION_NAMESPACE
  displayName: Cluster Version Namespace
  description: The namespace where the cluster version lives.
  value: openshift-cluster-operator
  required: true
- name: CLUSTER_CERT
  required: true
  description: Base64 encoded certificate for the cluster.
- name: CLUSTER_PRIVATE_KEY
  required: true
  description: Base64 encoded private key for the cluster.
- name: AWS_ACCESS_KEY_ID
  required: true
  description: Base64 encoded AWS access key ID that can be used to provision cluster resources.
- name: AWS_SECRET_ACCESS_KEY
  required: true
  description: Base64 encoded AWS secret access key that can be used to provision cluster resources.
- name: SSH_PRIVATE_KEY
  required: true
  description: Base64 encoded SSH private key that can be used to access the provisioned servers.
- name: SSH_PUBLIC_KEY
  required: true
  description: Base64 encoded SSH public key that can be used to access the provisioned servers.
- name: SSH_KEYPAIR_NAME
  required: false
  description: Name of AWS keypair to use for machines in this cluster.

objects:

# Secret to pass the SSL certs to the API Server
- apiVersion: v1
  kind: Secret
  metadata:
    name: ${CLUSTER_NAME}-certs
    namespace: ${CLUSTER_NAMESPACE}
  type: Opaque
  data:
    server.crt: ${CLUSTER_CERT}
    server.key: ${CLUSTER_PRIVATE_KEY}
    # NOTE: not setting ca.crt here as we're using self-signed certs for test clusters

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${CLUSTER_NAME}-aws-creds
    namespace: ${CLUSTER_NAMESPACE}
  type: Opaque
  data:
    awsAccessKeyId: ${AWS_ACCESS_KEY_ID}
    awsSecretAccessKey: ${AWS_SECRET_ACCESS_KEY}

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${CLUSTER_NAME}-ssh-key
    namespace: ${CLUSTER_NAMESPACE}
    labels:
      app: cluster-operator
  type: Opaque
  data:
    ssh-privatekey: ${SSH_PRIVATE_KEY}
    ssh-publickey: ${SSH_PUBLIC_KEY}

- apiVersion: clusteroperator.openshift.io/v1alpha1
  kind: ClusterDeployment
  metadata:
    name: ${CLUSTER_NAME}
    namespace: ${CLUSTER_NAMESPACE}
  spec:
    clusterVersionRef:
      namespace: ${CLUSTER_VERSION_NAMESPACE}
      name: ${CLUSTER_VERSION}
    networkConfig:
      services:
        cidrBlocks:
          - "172.30.0.0/16"
      pods:
        cidrBlocks:
          - "10.128.0.0/14"
    hardware:
      aws:
        accountSecret:
          name: ${CLUSTER_NAME}-aws-creds
        sshSecret:
          name: ${CLUSTER_NAME}-ssh-key
        sshUser: centos
        sslSecret:
          name: ${CLUSTER_NAME}-certs
        region: "us-east-1"
        keyPairName: ${SSH_KEYPAIR_NAME}
    defaultHardwareSpec:
      aws:
        instanceType: "t2.xlarge"
    machineSets:
    - nodeType: Master
      size: 1
    - shortName: infra
      nodeType: Compute
      infra: true
      size: 1
    - shortName: compute
      nodeType: Compute
      size: 1

